[package]
name = "memson"
version = "0.1.0"
authors = ["jaupe <jaupe@protonmail.com>"]
edition = "2018"

[dependencies]
bincode = "*"
rayon = "*"
actix-web = "3"
serde_json = "*"
serde = { version = "*", features = ["derive"] }
sled = "*"

[dev-dependencies]
assert_approx_eq = "*"